series: Intermediate C++
title: Lambda Expressions
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Lambda Expressions give a convenient shorthand for functors.
language: C++
tags:
  - Core
extra_resources:
  - link: https://msdn.microsoft.com/en-us/library/dd293608.aspx
    title: MSDN: lambda expressions
  - link: http://stackoverflow.com/questions/4686507/lambda-expression-vs-functor-in-c
    title: Stack Overflow: Functors vs Lambdas
  - link: http://www.cplusplus.com/reference/algorithm/
    title: STL reference: algorithm header
connections:
  - series: Intermediate C++
    title: Functors
  - series: Intermediate C++
    title: Class Templates